Feature: recherche par comptes de propriétés
3liz/lizmap-cadastre-module pull request #31
Opened 2021-06-10 10:25 UTC by rldhont

Financé par le Conseil Départemental du Calvados

2021-06-10 12:30 UTC, mdouchin requested changes
Il manque la modification du CHANGELOG

Je vais tester et faire un retour

2021-06-10 12:43 UTC, rldhont commented
@mdouchin done

2021-06-10 13:37 UTC, mdouchin approved these changes

2021-06-14 08:15 UTC, drillinP approved these changes

2021-06-14 09:25 UTC, merged