Application du paramètre sql du datasource des couches Communes, Sections, Parcelles
3liz/lizmap-cadastre-module pull request #76
Opened 2022-10-26 14:22 UTC by rldhont

Funded by AGAPE

2022-10-27 13:51 UTC, mdouchin requested changes

2022-10-27 13:51 UTC, mdouchin commented on cadastre/classes/cadastreExtraInfos.class.php
> +        }
```suggestion
            $sql .= ' AND (';
            $sql .= $this->getFilterSql($pFilterConfig, $profile);
            $sql .= ')'
        }
        if ($condition) {
            $sql .= ' AND (' . $condition . ')';
        }
```

2022-10-27 13:51 UTC, mdouchin commented on cadastre/classes/search.class.php
> +                }
```suggestion
                if ($condition) {
                    $sql .= ' AND (' . $condition . ')';
                }
```

2022-10-27 13:51 UTC, mdouchin commented on cadastre/classes/search.class.php
> +                }
```suggestion
                if ($condition) {
                    $sql .= ' AND (' . $condition .')';
                }
```

2022-10-27 13:51 UTC, mdouchin commented on cadastre/classes/search.class.php
> +                }
```suggestion
                if ($condition) {
                    $sql .= ' AND (' . $condition . ')';
                }
```

2022-10-27 13:51 UTC, mdouchin commented on cadastre/classes/search.class.php
> +            }
```suggestion
            if ($condition) {
                $sql .= ' AND (' . $condition . ')';
            }
```

2022-10-27 13:51 UTC, mdouchin commented on cadastre/classes/search.class.php
> +            }
```suggestion
            if ($condition) {
                $sql .= ' AND (' . $condition .')';
            }
```

2022-10-27 13:51 UTC, mdouchin commented on cadastre/classes/search.class.php
> +            }
```suggestion
            if ($condition) {
                $sql .= ' AND (' . $condition .')';
            }
```

2022-11-07 16:25 UTC, rldhont commented
@mdouchin changes requested applied!

2022-11-15 13:48 UTC, mdouchin approved these changes

2022-11-15 14:45 UTC, merged