Relevé pour un tiers
3liz/lizmap-cadastre-module pull request #79
Opened 2022-11-15 15:18 UTC by rldhont

Ajout de la possibilité de faire un relevé pour un tiers.

Funded by Calvados https://www.calvados.fr

2022-11-15 19:39 UTC, mdouchin requested changes

2022-11-15 19:39 UTC, mdouchin commented on cadastre/install/install_1_6.php
> +            jAcl2DbManager::addSubject('cadastre.acces.donnees.proprio.simple', 'cadastre~search.cadastre.acces.donnees.proprio.simple', 'cadastre.subject.group');
Please add a new file upgrade-XXX.php which will add the needed rights for already installed cadastre module

2022-11-15 19:39 UTC, mdouchin commented on cadastre/locales/en_US/search.UTF-8.properties
> +cadastre.acces.donnees.proprio=Accéder aux données de propriétaires avancées
```suggestion
cadastre.acces.donnees.proprio.simple=Accéder aux données de propriétaires simplifiées
cadastre.acces.donnees.proprio=Accéder aux données de propriétaires avancées
```

2022-11-15 19:39 UTC, mdouchin commented on cadastre/locales/fr_FR/search.UTF-8.properties
> +cadastre.acces.donnees.proprio=Accéder aux données de propriétaires avancées
```suggestion
cadastre.acces.donnees.proprio.simple=Accéder aux données de propriétaires simplifiées
cadastre.acces.donnees.proprio=Accéder aux données de propriétaires avancées
```

2022-11-16 08:46 UTC, rldhont commented
@mdouchin thanks for the review

2022-11-16 14:01 UTC, rldhont commented
@mdouchin changes requested done.

2022-11-16 14:22 UTC, mdouchin approved these changes

2022-11-17 11:09 UTC, laurentj approved these changes
ok for the upgrader

2022-11-17 11:10 UTC, rldhont commented
Merci @laurentj

2022-11-17 11:25 UTC, merged