[Bugfix] Renvois d'un tableau vide si certains paramètres pour une Datasource sont vide
3liz/lizmap-cadastre-module pull request #80
Opened 2022-11-16 13:45 UTC by rldhont

Lorsque certains paramètres de Datasource::getData sont vides, il n'est pas nécessaire de calculer et exécuter une requête, spécialement pour les Parcelles.

Funded by Calvados https://www.calvados.fr

2022-11-16 13:51 UTC, mdouchin requested changes

2022-11-16 13:51 UTC, mdouchin commented on CHANGELOG.md
> +* Lorsque certains paramètres de récupérations des données de Datasource sont vides renvoit rapide d'une liste vide.
```suggestion
* Lorsque certains paramètres de récupération des données du `datasource` de la couche
   QGIS sont vides, on renvoie directement une liste vide.
```

2022-11-16 14:05 UTC, Gustry reviewed
Minor review ;-)

2022-11-16 14:05 UTC, Gustry commented on cadastre/classes/listParcelleLieuDatasource.class.php
> +            return $result;
```suggestion
            return array();
```

Mineur, mais je préfère cette notation, je trouve que on lit plus vite "retourne une liste vide".
Et descendre la déclaration de `$result` quand on en a vraiment besoin pour modifier la liste. On ne se pose pas la question si `$result` est modifié entre les lignes L31 et L65.

Idem pour les autres dans ce PR.

My 2 cents, feel free to skip :)

2022-11-16 14:08 UTC, rldhont commented on cadastre/classes/listParcelleLieuDatasource.class.php
> +            return $result;
@Gustry en gros faire comme avant ;-)

2022-11-16 14:10 UTC, rldhont commented on CHANGELOG.md
> +* Lorsque certains paramètres de récupérations des données de Datasource sont vides renvoit rapide d'une liste vide.
Ce n'est pas le datasource d'une couche QGIS mais d'un champs jelix.

2022-11-16 14:14 UTC, rldhont commented
@mdouchin @Gustry done

2022-11-16 14:19 UTC, Gustry approved these changes
Neat ! ;-)

2022-11-16 14:19 UTC, Gustry commented on CHANGELOG.md
> +* Lorsque certains paramètres de récupération des données du Datasource d'un champs Jelix sont vides, on renvoie directement une liste vide.
```suggestion
* Lorsque certains paramètres de récupération des données du "Datasource" d'un champ Jelix sont vides, on renvoie directement une liste vide.
```

2022-11-17 10:33 UTC, rldhont commented
@Gustry Changelog changed

2022-11-17 10:35 UTC, merged