Modification requête
3liz/lizmap-cadastre-module pull request #9
Opened 2020-11-19 15:00 UTC by drillinP

* Modification de la requête de recherche par propriétaire pour ajouter la possibilité de rechercher par numéro de propriétaire
*

2021-03-12 14:59 UTC, rldhont commented
@drillinP il semble qu'un rebase soit nécessaire

2021-03-18 13:03 UTC, drillinP commented
Il manque que les erreurs eslint à corriger

2021-04-12 06:59 UTC, mdouchin requested changes
Ok pour moi mais

* corriger CI eslint
* si on veut chercher dans le compte-communal, voir si veut faire un LIKE sur "commence par", "finit par" ou "contient" -> adapter selon demande cc @rldhont

2021-04-16 15:47 UTC, rldhont commented
Pour le LIKE seulement le commence par. Donc le code PHP est bon.

2021-04-20 02:44 UTC, Gustry commented on cadastre/www/cadastre.js
> +/* eslint-disable */
C'est mieux de ne désactiver que ce qui ne va pas, plutôt que tout désactiver.
https://stackoverflow.com/questions/27732209/turning-off-eslint-rule-for-a-specific-line/29592334#29592334
Possible de désactiver seulement l'erreur en question ?
Bonus si il y a un petit commentaire qui explique :)

2021-04-23 08:35 UTC, Gustry approved these changes
LGTM pour la partie CI

2021-04-23 08:45 UTC, mdouchin approved these changes

2021-04-23 08:47 UTC, mdouchin commented
@drillinP peux tu stp faire un rebase et renommer le commit unique "Recherche par propriétaire - recherche aussi dans le champ comptecommunal"

2021-04-27 07:56 UTC, merged